### ISSUE TITLE
Issue with newer golang

### ISSUE THREAD

**Issue by hvonw** [wrfly/gus-proxy#8]
Hi @wrfly,
Spews error when trying to import proxies from file.

": net/url: invalid control character in URL "

**Comment by wrfly** [comment]
hi @hvonw , can I see your proxy file example?

**Comment by hvonw** [comment]
Hi friend,
As you said in the document it starts with the type.
Multiple proxy types all in one proxies.txt file.

```
http://IP:Port
socks4://IP:Port
socks5://IP:Port
```

The old version of the golang does not give this error by the way.
Maybe this could be the issue? (\r)
https://github.com/zserge/lorca/issues/51#issuecomment-476694915

**Comment by wrfly** [comment]
Got it, will fix it right away.

See also https://stackoverflow.com/questions/55945325/golang-url-parse-always-return-invalid-control-character-url
